spring:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

  datasource:
    driver-class-name: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

  h2:
    console:
      enabled: false
      path: /h2-console

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: ${API_PORT}
  servlet:
    context-path: ${API_CONTEXT_PATH}

springdoc:
  swagger-ui:
    path: swagger-ui-custom.html
    operationsSorter: method

