spring:
  datasource:
    driver-class-name: { DATABASE_DRIVER }
    url: { DATABASE_URL }
    username: { DATABASE_USERNAME }
    password: { DATABASE_PASSWORD }

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /api/v1