spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bloodbank
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    context-path: /api/v1